<script lang="ts" setup>
import type { OptimizeForm } from '../typing';

import { ref, watch } from 'vue';

import { useI18n } from '@vben/locales';

import { ElCol, ElFormItem, ElRow, ElSlider } from 'element-plus';

const props = defineProps<{
  model: OptimizeForm;
}>();

const emit = defineEmits(['update:model']);

const localModel = ref();

watch(
  () => props.model,
  (newModel) => {
    const newModelString = JSON.stringify(newModel);
    if (newModelString !== JSON.stringify(localModel.value)) {
      localModel.value = JSON.parse(newModelString);
    }
  },
  { deep: true, immediate: true },
);

watch(
  localModel,
  (newLocalModel) => {
    const propsModelString = JSON.stringify(props.model);
    if (propsModelString !== JSON.stringify(newLocalModel)) {
      emit('update:model', newLocalModel);
    }
  },
  { deep: true },
);

const { t } = useI18n();
</script>

<template>
  <div class="bounds-group p-4">
    <ElRow :gutter="40">
      <ElCol :span="12">
        <div class="mb-2 text-center font-bold">
          {{ t('page.passivbot.v7.optimizePage.form.boundsLong') }}
        </div>
        <ElFormItem
          :label="t('page.passivbot.v7.optimizePage.form.longNPositions')"
        >
          <ElSlider
            v-model="localModel.long_n_positions"
            :max="100"
            :min="0"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.longTotalWalletExposureLimit',
            )
          "
        >
          <ElSlider
            v-model="localModel.long_total_wallet_exposure_limit"
            :max="100"
            :min="0"
            :step="0.1"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="t('page.passivbot.v7.optimizePage.form.longUnstuckClosePct')"
        >
          <ElSlider
            v-model="localModel.long_unstuck_close_pct"
            :max="1"
            :min="0"
            :step="0.001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="t('page.passivbot.v7.optimizePage.form.longUnstuckEmaDist')"
        >
          <ElSlider
            v-model="localModel.long_unstuck_ema_dist"
            :max="1"
            :min="-1"
            :step="0.001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.longUnstuckLossAllowancePct')
          "
        >
          <ElSlider
            v-model="localModel.long_unstuck_loss_allowance_pct"
            :max="1"
            :min="0"
            :step="0.001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="t('page.passivbot.v7.optimizePage.form.longUnstuckThreshold')"
        >
          <ElSlider
            v-model="localModel.long_unstuck_threshold"
            :max="1"
            :min="-1"
            :step="0.001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.longFilterNoisinessRollingWindow',
            )
          "
        >
          <ElSlider
            v-model="localModel.long_filter_noisiness_rolling_window"
            :max="10000"
            :min="0"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.longFilterVolumeDropPct')
          "
        >
          <ElSlider
            v-model="localModel.long_filter_volume_drop_pct"
            :max="1"
            :min="0"
            :step="0.01"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.longFilterVolumeRollingWindow',
            )
          "
        >
          <ElSlider
            v-model="localModel.long_filter_volume_rolling_window"
            :max="10000"
            :min="0"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.longEntryGridDoubleDownFactor',
            )
          "
        >
          <ElSlider
            v-model="localModel.long_entry_grid_double_down_factor"
            :max="10"
            :min="0"
            :step="0.001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.longEntryGridSpacingPct')
          "
        >
          <ElSlider
            v-model="localModel.long_entry_grid_spacing_pct"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.longEntryGridSpacingWeight')
          "
        >
          <ElSlider
            v-model="localModel.long_entry_grid_spacing_weight"
            :max="100"
            :min="0"
            :step="0.0001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.longEntryInitialEmaDist')
          "
        >
          <ElSlider
            v-model="localModel.long_entry_initial_ema_dist"
            :max="1"
            :min="-1"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.longEntryInitialQtyPct')
          "
        >
          <ElSlider
            v-model="localModel.long_entry_initial_qty_pct"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.longEntryTrailingDoubleDownFactor',
            )
          "
        >
          <ElSlider
            v-model="localModel.long_entry_trailing_double_down_factor"
            :max="10"
            :min="0"
            :step="0.0001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.longEntryTrailingGridRatio')
          "
        >
          <ElSlider
            v-model="localModel.long_entry_trailing_grid_ratio"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.longEntryTrailingRetracementPct',
            )
          "
        >
          <ElSlider
            v-model="localModel.long_entry_trailing_retracement_pct"
            :max="1"
            :min="0"
            :step="0.00000001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.longEntryTrailingThresholdPct',
            )
          "
        >
          <ElSlider
            v-model="localModel.long_entry_trailing_threshold_pct"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.longCloseTrailingGridRatio')
          "
        >
          <ElSlider
            v-model="localModel.long_close_trailing_grid_ratio"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.longCloseTrailingQtyPct')
          "
        >
          <ElSlider
            v-model="localModel.long_close_trailing_qty_pct"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.longCloseTrailingRetracementPct',
            )
          "
        >
          <ElSlider
            v-model="localModel.long_close_trailing_retracement_pct"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.longCloseTrailingThresholdPct',
            )
          "
        >
          <ElSlider
            v-model="localModel.long_close_trailing_threshold_pct"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="t('page.passivbot.v7.optimizePage.form.longEmaSpan0')"
        >
          <ElSlider
            v-model="localModel.long_ema_span_0"
            :max="10000"
            :min="0"
            :step="0.01"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="t('page.passivbot.v7.optimizePage.form.longEmaSpan1')"
        >
          <ElSlider
            v-model="localModel.long_ema_span_1"
            :max="10000"
            :min="0"
            :step="0.01"
            range
          />
        </ElFormItem>
      </ElCol>

      <ElCol :span="12">
        <div class="mb-2 text-center font-bold">
          {{ t('page.passivbot.v7.optimizePage.form.boundsShort') }}
        </div>
        <ElFormItem
          :label="t('page.passivbot.v7.optimizePage.form.shortNPositions')"
        >
          <ElSlider
            v-model="localModel.short_n_positions"
            :max="100"
            :min="0"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.shortTotalWalletExposureLimit',
            )
          "
        >
          <ElSlider
            v-model="localModel.short_total_wallet_exposure_limit"
            :max="100"
            :min="0"
            :step="0.1"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="t('page.passivbot.v7.optimizePage.form.shortUnstuckClosePct')"
        >
          <ElSlider
            v-model="localModel.short_unstuck_close_pct"
            :max="1"
            :min="0"
            :step="0.001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="t('page.passivbot.v7.optimizePage.form.shortUnstuckEmaDist')"
        >
          <ElSlider
            v-model="localModel.short_unstuck_ema_dist"
            :max="1"
            :min="-1"
            :step="0.001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.shortUnstuckLossAllowancePct',
            )
          "
        >
          <ElSlider
            v-model="localModel.short_unstuck_loss_allowance_pct"
            :max="1"
            :min="0"
            :step="0.001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.shortUnstuckThreshold')
          "
        >
          <ElSlider
            v-model="localModel.short_unstuck_threshold"
            :max="1"
            :min="-1"
            :step="0.001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.shortFilterNoisinessRollingWindow',
            )
          "
        >
          <ElSlider
            v-model="localModel.short_filter_noisiness_rolling_window"
            :max="10000"
            :min="0"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.shortFilterVolumeDropPct')
          "
        >
          <ElSlider
            v-model="localModel.short_filter_volume_drop_pct"
            :max="1"
            :min="0"
            :step="0.01"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.shortFilterVolumeRollingWindow',
            )
          "
        >
          <ElSlider
            v-model="localModel.short_filter_volume_rolling_window"
            :max="10000"
            :min="0"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.shortEntryGridDoubleDownFactor',
            )
          "
        >
          <ElSlider
            v-model="localModel.short_entry_grid_double_down_factor"
            :max="10"
            :min="0"
            :step="0.001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.shortEntryGridSpacingPct')
          "
        >
          <ElSlider
            v-model="localModel.short_entry_grid_spacing_pct"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.shortEntryGridSpacingWeight')
          "
        >
          <ElSlider
            v-model="localModel.short_entry_grid_spacing_weight"
            :max="100"
            :min="0"
            :step="0.0001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.shortEntryInitialEmaDist')
          "
        >
          <ElSlider
            v-model="localModel.short_entry_initial_ema_dist"
            :max="1"
            :min="-1"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.shortEntryInitialQtyPct')
          "
        >
          <ElSlider
            v-model="localModel.short_entry_initial_qty_pct"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.shortEntryTrailingDoubleDownFactor',
            )
          "
        >
          <ElSlider
            v-model="localModel.short_entry_trailing_double_down_factor"
            :max="10"
            :min="0"
            :step="0.0001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.shortEntryTrailingGridRatio')
          "
        >
          <ElSlider
            v-model="localModel.short_entry_trailing_grid_ratio"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.shortEntryTrailingRetracementPct',
            )
          "
        >
          <ElSlider
            v-model="localModel.short_entry_trailing_retracement_pct"
            :max="1"
            :min="0"
            :step="0.00000001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.shortEntryTrailingThresholdPct',
            )
          "
        >
          <ElSlider
            v-model="localModel.short_entry_trailing_threshold_pct"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.shortCloseTrailingGridRatio')
          "
        >
          <ElSlider
            v-model="localModel.short_close_trailing_grid_ratio"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t('page.passivbot.v7.optimizePage.form.shortCloseTrailingQtyPct')
          "
        >
          <ElSlider
            v-model="localModel.short_close_trailing_qty_pct"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.shortCloseTrailingRetracementPct',
            )
          "
        >
          <ElSlider
            v-model="localModel.short_close_trailing_retracement_pct"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="
            t(
              'page.passivbot.v7.optimizePage.form.shortCloseTrailingThresholdPct',
            )
          "
        >
          <ElSlider
            v-model="localModel.short_close_trailing_threshold_pct"
            :max="1"
            :min="0"
            :step="0.00001"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="t('page.passivbot.v7.optimizePage.form.shortEmaSpan0')"
        >
          <ElSlider
            v-model="localModel.short_ema_span_0"
            :max="10000"
            :min="0"
            :step="0.01"
            range
          />
        </ElFormItem>
        <ElFormItem
          :label="t('page.passivbot.v7.optimizePage.form.shortEmaSpan1')"
        >
          <ElSlider
            v-model="localModel.short_ema_span_1"
            :max="10000"
            :min="0"
            :step="0.01"
            range
          />
        </ElFormItem>
      </ElCol>
    </ElRow>
  </div>
</template>
